# Generated by Django 4.2 on 2023-05-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=64)),
                ('horario', models.TimeField()),
                ('dia', models.IntegerField()),
                ('nombre_profesor', models.CharField(max_length=64)),
                ('telefono_contacto', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Salones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=64)),
                ('horario', models.TimeField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('cedula_de_identidad', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=64)),
                ('celular', models.CharField(max_length=20)),
                ('numero_socio', models.CharField(max_length=128)),
                ('es_socio', models.BooleanField(default=False)),
            ],
        ),
    ]
