# Generated by Django 4.2 on 2023-05-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_once_estrellas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionSocios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficios', models.TextField()),
                ('cuota_social', models.DecimalField(decimal_places=2, max_digits=8)),
                ('formas_pago', models.CharField(max_length=100)),
            ],
        ),
    ]
