# Generated by Django 4.2 on 2023-05-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_once_estrellas', '0002_informacionsocios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='actividades/')),
                ('descripcion', models.TextField()),
                ('nombre_profesor', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
            ],
        ),
    ]
