# Generated by Django 4.2.1 on 2023-05-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_once_estrellas', '0004_actividad_creador_actividades_creador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='dia',
            field=models.CharField(max_length=64),
        ),
    ]
