# Generated by Django 4.2 on 2023-05-31 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_once_estrellas', '0005_alter_actividades_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='creador',
        ),
        migrations.AddField(
            model_name='actividades',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='actividades',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividades',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividades',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='actividades'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
    ]
