# Generated by Django 4.2 on 2023-06-02 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_once_estrellas', '0008_comentario_articulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to=settings.AUTH_USER_MODEL),
        ),
    ]
