# Generated by Django 4.2 on 2023-06-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_once_estrellas', '0010_alter_actividades_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='autor',
            new_name='usuario',
        ),
    ]
