# Generated by Django 4.2 on 2023-06-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_once_estrellas', '0012_remove_articulos_usuario_articulos_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='autor',
            field=models.CharField(max_length=100),
        ),
    ]
