# Generated by Django 4.2 on 2023-06-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_once_estrellas', '0017_remove_articulos_autor_id_articulos_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='autor',
            field=models.CharField(max_length=100),
        ),
    ]
